version: '3.8'

services:
  node-backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: bash -c "freshclam && service clamav-daemon start && node server.js"
